#nelmio_api_doc:
#    areas:
#            default:
#                path_patterns: [^/api]
#                host_patterns: [api\.]
#
#    documentation:
#            host: dev.aymen/api/
#            info:
#                title: Consults API
#                description: This is Consults API REST!
#                version: 1.0.0
#            basePath:
#            schemes:
#              - http
#            paths:
#              /categories:
#                get:
#                  tags:
#                    - categories
#                  operationId: categories
#                  summary: categories
#                  description: categories
#                  consumes:
#                    - application/json
#                  produces:
#                    - application/json
#                  responses:
#                    200:
#                      description: Found results

