version: '3'

services:
  app-server:
    build: ./dockerfile/server
    container_name: apache-php-app
    volumes:
      - ./:/var/www/html/myapp
    ports:
      - 8080:80
    networks:
      - default
      - some-net
  db-imgage:
    build: ./dockerfile/db/
    container_name: dbase-app
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
      - some-net
  varnish:
    build: ./dockerfile/varnish/
    container_name: cache-server
    ports:
      - "80:6081"
    links:
      - app-server
    environment:
      - BACKENDS_PROBE_INTERVAL=3s
      - BACKENDS_PROBE_TIMEOUT=1s
      - BACKENDS_PROBE_WINDOW=3
      - BACKENDS_PROBE_THRESHOLD=2
    networks:
      - default
      - some-net

networks:
  some-net:
    driver: bridge
  default:
    driver: bridge
