#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

homepage:
    path: /
    controller: App\Controller\HomeController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

category:
    resource: 'App\Controller\CategoryController'
    type:     rest
    prefix: /

consultant:
    resource: 'App\Controller\ConsultantController'
    type:     rest
    prefix: /

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
