#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

homepage:
    resource: 'App\Controller\CategoryController'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

Category:
    resource: 'App\Controller\CategoryController'
    type:     rest

Consultant:
    resource: 'App\Controller\ConsultantController'
    type:     rest

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
